[project]
name = "fusion-poke-pixel-font"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "pixel-font-builder==0.0.61",
    "pixel-font-knife==0.0.31",
    "fonttools[woff]==4.66.0",
    "unicodedata2==18.0.0",
    "unidata-blocks==0.0.27",
    "pyyaml==6.0.3",
    "pillow==12.3.0",
    "httpx[http2]==0.28.1",
    "tqdm==4.70.1",
    "loguru==0.7.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
