# 汉字
-
  font-size: 10
  dir-from: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  width-mode-dir-name: common
  flavor: zh_hk,zh_tw,zh_tr
-
  font-size: 10
  dir-from: galmuri/4E00-9FFF CJK Unified Ideographs
  width-mode-dir-name: common
  flavor: ko
-
  font-size: 12
  dir-from: cubic-11/4E00-9FFF CJK Unified Ideographs
  width-mode-dir-name: common
  flavor: zh_hk,zh_tw,zh_tr
-
  font-size: 12
  dir-from: galmuri/4E00-9FFF CJK Unified Ideographs
  width-mode-dir-name: common
  flavor: ko

# 谚文
-
  font-size: 10
  dir-from: galmuri/AC00-D7AF Hangul Syllables
  width-mode-dir-name: common
-
  font-size: 12
  dir-from: galmuri/AC00-D7AF Hangul Syllables
  width-mode-dir-name: common
